sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gratiangaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gratiangaga/react-test npm test -- --coverage

after_success:
  - docker build -t gratiangaga/multi-client ./client
  - docker build -t gratiangaga/multi-nginx ./nginx
  - docker build -t gratiangaga/multi-server ./server
  - docker build -t gratiangaga/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gratiangaga/multi-client
  - docker push gratiangaga/multi-nginx
  - docker push gratiangaga/multi-server
  - docker push gratiangaga/multi-worker
